{% set name = "lunardate" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f092417850973eb58e1eaee0c13dd50ab9d1cae35ed348ff5840e8e1e322fe6a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - lunardate

about:
  home: https://github.com/lidaobing/python-lunardate
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'A Chinese Calendar Library in Pure Python'


extra:
  recipe-maintainers:
    - bletham
